# GestionASM17/config/routes.yaml

accueil:
    path : /accueil
    controller : App\Controller\GestionASM17Controller::accueil

membres:
    path: /membres
    controller: App\Controller\MembresController::afficherMembres
    