# GestionASM17/config/routes.yaml

accueil:
    path : /accueil
    controller : App\Controller\GestionASM17Controller::accueil

membres:
    path: /membres
    controller: App\Controller\MembresController::afficherMembres

detail_membres:
    path: /membres/{id}
    controller : App\Controller\MembresController::detailMembres
    # requirements:
    #     id: 'd\+'

ajouter_adherent:
    path: /ajouterAdherent
    controller: App\Controller\AdherentController::ajouterAdherent
    
donateurs:
    path: /donateurs
    controller: App\Controller\DonateursController::afficherDonateurs
    
detail_donateurs:
    path: /donateurs/{id}
    controller: App\Controller\DonateursController::detailDonateurs

professionnels:
    path: /professionnels
    controller : App\Controller\ProfessionnelsController::afficherProfessionnels

detail_professionnels:
    path : /professionnels/{id}
    controller : App\Controller\ProfessionnelsController::detailProfessionnels

depenses:
    path : /depenses
    controller : App\Controller\DepenseController::afficherDepenses

detail_depenses:
    path: /depense/{id}
    controller : App\Controller\DepenseController::detailDepenses

ajouter_depense :
    path: /ajouterDepense
    controller : App\Controller\DepenseController::ajouterDepense

changer_ExerciceComptable:
    path: /exerciceComptable
    controller : App\Controller\ExerciceComptableEnCoursController::changerExerciceComptable

ajouter_banque:
    path: /ajouterBanque
    controller : App\Controller\BanqueController::ajouterBanque

rapprocher_depense:
    path : /rapprocherDepense
    controller : App\Controller\DepenseController::rapprocherDepense