# GestionASM17/config/routes.yaml

accueil:
    path : /accueil
    controller : App\Controller\GestionASM17Controller::accueil

membres:
    path: /membres
    controller: App\Controller\MembresController::afficherMembres

detail_membres:
    path: /membres/{id}
    controller : App\Controller\MembresController::detailMembres
    # requirements:
    #     id: 'd\+'

donateurs:
    path: /donateurs
    controller: App\Controller\DonateursController::afficherDonateurs
    
detail_donateurs:
    path: /donateurs/{id}
    controller: App\Controller\DonateursController::detailDonateurs

professionnels:
    path: /professionnels
    controller : App\Controller\ProfessionnelsController::afficherProfessionnels

detail_professionnels:
    path : /professionnels/{id}
    controller : App\Controller\ProfessionnelsController::detailProfessionnels

changer_ExerciceComptable:
    path: /exerciceComptable
    controller : App\Controller\ExerciceComptableEnCoursController::changerExerciceComptable