# GestionASM17/config/routes.yaml

#index:
#    path: /
#    controller: App\Controller\DefaultController::index

accueil:
    path : /accueil
    controller : App\Controller\GestionASM17Controller::accueil
    