# GestionASM17/config/routes.yaml

accueil:
    path : /accueil
    controller : App\Controller\GestionASM17Controller::accueil

membres:
    path: /membres
    controller: App\Controller\MembresController::afficherMembres

detail_membres:
    path: /membres/{id}
    controller : App\Controller\MembresController::detailMembres
    # requirements:
    #     id: 'd\+'

ajouter_adherent:
    path: /ajouterAdherent
    controller: App\Controller\AdherentController::ajouterAdherent
    
donateurs:
    path: /donateurs
    controller: App\Controller\DonateursController::afficherDonateurs
    
detail_donateurs:
    path: /donateurs/{id}
    controller: App\Controller\DonateursController::detailDonateurs

professionnels:
    path: /professionnels
    controller : App\Controller\ProfessionnelsController::afficherProfessionnels

detail_professionnels:
    path : /professionnels/{id}
    controller : App\Controller\ProfessionnelsController::detailProfessionnels

ajouter_professionnels:
    path : /ajouterProfessionnel
    controller : App\Controller\ProfessionnelControler::ajouterProfessionnels

depenses:
    path : /depenses
    controller : App\Controller\DepenseController::afficherDepenses

detail_depenses:
    path: /depense/{id}
    controller : App\Controller\DepenseController::detailDepenses

ajouter_depense :
    path: /ajouterDepense
    controller : App\Controller\DepenseController::ajouterDepense

changer_ExerciceComptable:
    path: /exerciceComptable
    controller : App\Controller\ExerciceComptableEnCoursController::changerExerciceComptable

ajouter_banque:
    path: /ajouterBanque
    controller : App\Controller\BanqueController::ajouterBanque

liste_depenses_a_rapprocher:
    path : /depenseARapprocher
    controller : App\Controller\DepenseController::listeDepensesNonRapprochées

rapprocher_depenses:
    path : /depenseARapprocher/{id}
    controller : App\Controller\DepenseController::rapprocherDepense

recettes:
    path : /recettes
    controller : App\Controller\RecetteController::afficherRecettes

detail_recettes:
    path: /recette/{id}
    controller : App\Controller\RecetteController::detailRecettes

ajouter_recette:
    path : /ajouterrecette
    controller : App\Controller\RecetteController::ajouterRecette

liste_recettes_a_rapprocher:
    path : /recetteARapprocher
    controller : App\Controller\RecetteController::listeRecettesNonRapprochees

rapprocher_recettes:
    path : /recettesARapprocher/{id}
    controller : App\Controller\RecetteController::rapprocherRecettes