# GestionASM17/config/routes.yaml

membres:
    path: /membres
    controller: App\Controller\DefaultController::membres

accueil:
    path : /accueil
    controller : App\Controller\GestionASM17Controller::accueil
    